name: graduation_project
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: ^2.1.5
  provider: ^4.3.2+3
  dio: ^3.0.9
  dio_cookie_manager: 1.0.0
  dio_retry: ^0.1.9-beta
  dio_http_cache: ^0.2.7
  dio_log: ^1.3.3
  cookie_jar: ^1.0.0
  flutter_screenutil: ^4.0.3+2
  shared_preferences: ^0.5.12+4
  cupertino_icons: ^0.1.3
  charts_flutter: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
